import { URI, expandToString } from 'langium';
import { createER2CDSServices } from '../er2cds-module.js';
import { Attribute, ER2CDS, Entity, Relationship, RelationshipJoinClause } from '../generated/ast.js';
import { ER2CDSFileSystem } from '../er2cds-file-system-provider.js';
import { MessageType } from 'vscode-languageserver-protocol';
import { connection } from '../server.js';

export async function generateCDS(fileName: string | undefined): Promise<void> {
    if (!fileName) {
        connection.sendNotification('window/showMessage', {
            type: MessageType.Error,
            message: 'No valid ER2CDS file opened.'
        });
        return;
    }

    const services = createER2CDSServices(ER2CDSFileSystem).ER2CDS;

    const fileUri = URI.parse(fileName);
    const document = services.shared.workspace.LangiumDocumentFactory.create(fileUri);
    await services.shared.workspace.DocumentBuilder.build([document], { validation: true })

    const parseResult = document.parseResult;
    if ((parseResult.parserErrors && parseResult.parserErrors.length > 0) || (parseResult.lexerErrors && parseResult.lexerErrors.length > 0)) {
        connection.sendNotification('window/showMessage', {
            type: MessageType.Error,
            message: 'Model contains errors. CDS cannot be generated.'
        });
        return;
    }

    const diagnostics = await services.validation.DocumentValidator.validateDocument(document);
    if (diagnostics.some(d => d.severity === 1)) {
        connection.sendNotification('window/showMessage', {
            type: MessageType.Error,
            message: 'Model contains errors. CDS cannot be generated.'
        });
        return;
    }

    const sourceCode = generateSourceCode(parseResult.value as ER2CDS);
    if (!sourceCode) {
        connection.sendNotification('window/showMessage', {
            type: MessageType.Error,
            message: 'CDS-Generation failed.'
        });
        return;
    }

    const fileNameWithExtension = fileUri.fsPath.substring(fileUri.fsPath.lastIndexOf('/') + 1, fileUri.fsPath.length);
    const fileNameWithoutExtension = fileNameWithExtension.substring(0, fileNameWithExtension.lastIndexOf('.'));

    const generatedFileName = fileNameWithoutExtension + '-generated.abapcds';
    const generatedFilePath = fileUri.fsPath.substring(0, fileUri.fsPath.lastIndexOf('/')) + '/' + generatedFileName;

    ER2CDSFileSystem.fileSystemProvider().writeFile(URI.parse(generatedFilePath), sourceCode);

    return Promise.resolve();
}

function generateSourceCode(model: ER2CDS): string | undefined {
    model.relationships.sort((r1, r2) => {
        if (r1.joinOrder && r2.joinOrder)
            return r1.joinOrder - r2.joinOrder;

        if (r1.joinOrder)
            return -1;

        if (r2.joinOrder)
            return 1;

        return 0;
    });

    return expandToString`
        ${generateHeaderAnnotations(model)}
        ${generateHeader(model)}
            ${generateFromClause(model)}
            ${generateJoins(model)}
            ${generateAssociations(model)}
            ${generateAssociationsToParent(model)}
            ${generateCompositions(model)}
        {
            ${generateKeyAttributes(model)}${model.entities.find(e => e.attributes.find(a => a.type === 'key')) && model.entities.find(e => e.attributes.find(a => a.type !== 'key')) ? ',' : ''}
            ${generateAttributes(model)}${model.entities.find(e => e.attributes.find(a => a.type !== 'key')) && model.relationships.find(r => r.type === 'association' || r.type === 'association-to-parent' || r.type === 'composition') ? ',' : ''}
            ${generateAssociationAttributes(model)}
        }
    `;
}

function generateHeaderAnnotations(model: ER2CDS): string | undefined {
    return expandToString`
        @AccessControl.authorizationCheck: #CHECK
        @Metadata.ignorePropagatedAnnotations: true
        @EndUserText.label: 'Generated by ER2CDS'
    `;
}

function generateHeader(model: ER2CDS): string | undefined {
    return expandToString`
        define view entity ${model.name} as select
    `;
}

function generateFromClause(model: ER2CDS): string | undefined {
    if (model.relationships && model.relationships.length > 0) {
        return expandToString`
            from ${model.relationships[0].source?.target.ref?.name} ${model.relationships[0].source?.target.ref?.alias ? `as ${model.relationships[0].source?.target.ref?.alias}` : undefined}
        `;
    } else {
        return expandToString`
            from ${model.entities[0].name} ${model.entities[0].alias ? `as ${model.entities[0].alias}` : undefined}
        `;
    }
}

function generateJoins(model: ER2CDS): string | undefined {
    if (model.relationships) {
        return model.relationships.filter(r => !r.type).map(r => {
            let join;

            if (r.source?.cardinality === '1' && r.target?.cardinality === '1') {
                join = generateInnerJoin(model, r);

            } else if (r.source?.cardinality === '1' && r.target?.cardinality === '0..N') {
                join = generateLeftJoin(model, r);

            } else if (r.source?.cardinality === '0..N' && r.target?.cardinality === '1') {
                join = generateRightJoin(model, r);

            } else if (r.source?.cardinality === '0..N' && r.target?.cardinality === '0..N') {
                join = generateLeftJoin(model, r);

            } else {
                join = generateInnerJoin(model, r);

            }

            return join;
        }).filter(Boolean).join('\n');
    }

    return undefined;
}

function generateInnerJoin(model: ER2CDS, relationship: Relationship): string | undefined {
    if (model.entities && model.entities.length > 0) {
        return expandToString`
            inner join ${relationship.target?.target.ref?.name}${relationship.target?.target.ref?.alias ? ` as ${relationship.target?.target.ref?.alias}` : undefined} on ${generateJoinClause(relationship, relationship.joinClauses)}
        `;
    }

    return undefined;
}

function generateLeftJoin(model: ER2CDS, relationship: Relationship): string | undefined {
    if (model.entities && model.entities.length > 0) {
        return expandToString`
            left outer join ${relationship.target?.target.ref?.name}${relationship.target?.target.ref?.alias ? ` as ${relationship.target?.target.ref?.alias}` : undefined} on ${generateJoinClause(relationship, relationship.joinClauses)}
        `;
    }

    return undefined;
}

function generateRightJoin(model: ER2CDS, relationship: Relationship): string | undefined {
    if (model.entities && model.entities.length > 0) {
        return expandToString`
            right outer join ${relationship.target?.target.ref?.name}${relationship.target?.target.ref?.alias ? ` as ${relationship.target?.target.ref?.alias}` : undefined} on ${generateJoinClause(relationship, relationship.joinClauses)}
        `;
    }

    return undefined;
}

function generateJoinClause(relationship: Relationship, joinClauses: RelationshipJoinClause[]): string | undefined {
    let joinClause;

    joinClause = joinClauses.map(jc => {
        return expandToString`
            ${relationship.source?.target.ref?.alias ? relationship.source?.target.ref?.alias : relationship.source?.target.ref?.name}.${jc.firstAttribute.ref?.name} = ${relationship.target?.target.ref?.alias ? relationship.target?.target.ref?.alias : relationship.target?.target.ref?.name}.${jc.secondAttribute.ref?.name}
        `
    }).filter(Boolean).join(' and ');

    return joinClause;
}

function generateAssociations(model: ER2CDS): string | undefined {
    if (model.relationships) {
        return model.relationships.filter(r => r.type === 'association').map(r => {
            let association;

            if (r.source?.cardinality === '1' && r.target?.cardinality === '1') {
                association = generateOneOneAssociation(model, r);

            } else if (r.source?.cardinality === '1' && r.target?.cardinality === '0..N') {
                association = generateOneManyAssociation(model, r);

            } else if (r.source?.cardinality === '0..N' && r.target?.cardinality === '1') {
                association = generateZeroOneAssociation(model, r);

            } else if (r.source?.cardinality === '0..N' && r.target?.cardinality === '0..N') {
                association = generateZeroManyAssociation(model, r);

            } else {
                association = generateZeroOneAssociation(model, r);

            }

            return association;
        }).filter(Boolean).join('\n');
    }

    return undefined;
}

function generateOneOneAssociation(model: ER2CDS, relationship: Relationship): string | undefined {
    if (model.entities && model.entities.length > 0) {
        return expandToString`
            association[1..1] to ${relationship.target?.target.ref?.name}${relationship.target?.target.ref?.alias ? ` as ${relationship.target?.target.ref?.alias}` : undefined} on ${generateAssociationClause(relationship, relationship.joinClauses)}
        `;
    }

    return undefined;
}

function generateOneManyAssociation(model: ER2CDS, relationship: Relationship): string | undefined {
    if (model.entities && model.entities.length > 0) {
        return expandToString`
            association[1..*] to ${relationship.target?.target.ref?.name}${relationship.target?.target.ref?.alias ? ` as ${relationship.target?.target.ref?.alias}` : undefined} on ${generateAssociationClause(relationship, relationship.joinClauses)}
        `;
    }

    return undefined;
}

function generateZeroOneAssociation(model: ER2CDS, relationship: Relationship): string | undefined {
    if (model.entities && model.entities.length > 0) {
        return expandToString`
            association[0..1] to ${relationship.target?.target.ref?.name}${relationship.target?.target.ref?.alias ? ` as ${relationship.target?.target.ref?.alias}` : undefined} on ${generateAssociationClause(relationship, relationship.joinClauses)}
        `;
    }

    return undefined;
}

function generateZeroManyAssociation(model: ER2CDS, relationship: Relationship): string | undefined {
    if (model.entities && model.entities.length > 0) {
        return expandToString`
            association[0..*] to ${relationship.target?.target.ref?.name}${relationship.target?.target.ref?.alias ? ` as ${relationship.target?.target.ref?.alias}` : undefined} on ${generateAssociationClause(relationship, relationship.joinClauses)}
        `;
    }

    return undefined;
}

function generateAssociationClause(relationship: Relationship, joinClauses: RelationshipJoinClause[]): string | undefined {
    let associationClause;

    associationClause = joinClauses.map(jc => {
        return expandToString`
            $projection.${jc.firstAttribute.ref?.alias ? jc.firstAttribute.ref?.alias : jc.firstAttribute.ref?.name} = ${relationship.target?.target.ref?.alias ? relationship.target?.target.ref?.alias : relationship.target?.target.ref?.name}.${jc.secondAttribute.ref?.name}
        `
    }).filter(Boolean).join(' and ');

    return associationClause;
}

function generateAssociationsToParent(model: ER2CDS): string | undefined {
    if (model.relationships) {
        return model.relationships.filter(r => r.type === 'association-to-parent').map(r => generateAssociationToParent(model, r)).filter(Boolean).join('\n');
    }

    return undefined;
}

function generateAssociationToParent(model: ER2CDS, relationship: Relationship): string | undefined {
    if (model.entities && model.entities.length > 0) {
        return expandToString`
            association to parent ${relationship.target?.target.ref?.name}${relationship.target?.target.ref?.alias ? ` as ${relationship.target?.target.ref?.alias}` : undefined} on ${generateAssociationClause(relationship, relationship.joinClauses)}
        `;
    }

    return undefined;
}

function generateCompositions(model: ER2CDS): string | undefined {
    if (model.relationships) {
        return model.relationships.filter(r => r.type === 'composition').map(r => {
            let association;

            if (r.source?.cardinality === '1' && r.target?.cardinality === '1') {
                association = generateOneOneComposition(model, r);

            } else if (r.source?.cardinality === '1' && r.target?.cardinality === '0..N') {
                association = generateOneManyComposition(model, r);

            } else if (r.source?.cardinality === '0..N' && r.target?.cardinality === '1') {
                association = generateZeroOneComposition(model, r);

            } else if (r.source?.cardinality === '0..N' && r.target?.cardinality === '0..N') {
                association = generateZeroManyComposition(model, r);

            } else {
                association = generateZeroManyComposition(model, r);

            }

            return association;
        }).filter(Boolean).join('\n');
    }

    return undefined;
}

function generateOneOneComposition(model: ER2CDS, relationship: Relationship): string | undefined {
    if (model.entities && model.entities.length > 0) {
        return expandToString`
            composition[1..1] of ${relationship.target?.target.ref?.name}${relationship.target?.target.ref?.alias ? ` as ${relationship.target?.target.ref?.alias}` : undefined}
        `;
    }

    return undefined;
}

function generateOneManyComposition(model: ER2CDS, relationship: Relationship): string | undefined {
    if (model.entities && model.entities.length > 0) {
        return expandToString`
            composition[1..*] of ${relationship.target?.target.ref?.name}${relationship.target?.target.ref?.alias ? ` as ${relationship.target?.target.ref?.alias}` : undefined}
        `;
    }

    return undefined;
}

function generateZeroOneComposition(model: ER2CDS, relationship: Relationship): string | undefined {
    if (model.entities && model.entities.length > 0) {
        return expandToString`
            composition[0..1] of ${relationship.target?.target.ref?.name}${relationship.target?.target.ref?.alias ? ` as ${relationship.target?.target.ref?.alias}` : undefined}
        `;
    }

    return undefined;
}

function generateZeroManyComposition(model: ER2CDS, relationship: Relationship): string | undefined {
    if (model.entities && model.entities.length > 0) {
        return expandToString`
            composition[0..*] of ${relationship.target?.target.ref?.name}${relationship.target?.target.ref?.alias ? ` as ${relationship.target?.target.ref?.alias}` : undefined}
        `;
    }

    return undefined;
}

function generateKeyAttributes(model: ER2CDS): string | undefined {
    if (model.entities) {
        let attributes: string[] = [];

        model.entities.forEach(e => {
            const keyFields = e.attributes.filter(a => a.type === 'key');

            if (keyFields.length > 0)
                attributes.push(keyFields.map(a => generateAttribute(e, a)).filter(Boolean).join(',\n'));
        });

        return attributes.filter(Boolean).join(',\n');
    }

    return undefined;
}

function generateAttributes(model: ER2CDS): string | undefined {
    if (model.entities) {
        let attributes: string[] = [];

        model.entities.forEach(e => {
            const nonKeyFields = e.attributes.filter(a => a.type !== 'key');

            if (nonKeyFields.length > 0) {
                attributes.push(nonKeyFields.map(a => generateAttribute(e, a)).filter(Boolean).join(',\n'));
            }
        });

        return attributes.filter(Boolean).join(',\n');
    }

    return undefined;
}

function generateAttribute(entity: Entity, attribute: Attribute): string | undefined {
    if (attribute.type !== 'no-out') {
        return expandToString`
            ${attribute.type === 'key' ? 'key' : ''} ${entity.alias ? entity.alias : entity.name}.${attribute.name} ${generateAttributeLabel(entity, attribute)}
        `;
    }

    return undefined;
}

function generateAttributeLabel(entity: Entity, attribute: Attribute): string | undefined {
    if (attribute.alias) {
        return expandToString`
            as ${attribute.alias}
        `;
    }

    return undefined;
}

function generateAssociationAttributes(model: ER2CDS): string | undefined {
    if (model.relationships) {
        let associationAttributes: string[] = [];

        model.relationships.filter(r => r.type === 'association' || r.type === 'association-to-parent' || r.type === 'composition').forEach(r => {
            associationAttributes.push(expandToString`${r.target?.target.ref?.alias ? r.target?.target.ref?.alias : r.target?.target.ref?.name}`);
        });

        return associationAttributes.filter(Boolean).join(',\n');
    }

    return undefined;
}